import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { TooltipProvider } from "@/components/ui/tooltip";
import RootProviders from "@/components/providers/RootProviders";
const geist = Geist({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <RootProviders>
      <html lang="en" className={cn("font-sans", geist.variable)}>
        <body className="min-h-full flex flex-col">{children}</body>
      </html>
    </RootProviders>
  );
}
