export const currencies = [
  { value: "USD", label: "USD — US Dollar", locale: "en-US" },
  { value: "EUR", label: "EUR — Euro", locale: "de-DE" },
  { value: "GBP", label: "GBP — British Pound", locale: "en-GB" },
  { value: "JPY", label: "JPY — Japanese Yen", locale: "ja-JP" },
  { value: "CNY", label: "CNY — Chinese Yuan", locale: "zh-CN" },
  { value: "CHF", label: "CHF — Swiss Franc", locale: "de-CH" },
  { value: "CAD", label: "CAD — Canadian Dollar", locale: "en-CA" },
  { value: "AUD", label: "AUD — Australian Dollar", locale: "en-AU" },
  { value: "NZD", label: "NZD — New Zealand Dollar", locale: "en-NZ" },
  { value: "SEK", label: "SEK — Swedish Krona", locale: "sv-SE" },
  { value: "NOK", label: "NOK — Norwegian Krone", locale: "nb-NO" },
  { value: "DKK", label: "DKK — Danish Krone", locale: "da-DK" },
  { value: "PLN", label: "PLN — Polish Złoty", locale: "pl-PL" },
  { value: "CZK", label: "CZK — Czech Koruna", locale: "cs-CZ" },
  { value: "HUF", label: "HUF — Hungarian Forint", locale: "hu-HU" },
  { value: "TRY", label: "TRY — Turkish Lira", locale: "tr-TR" },
  { value: "INR", label: "INR — Indian Rupee", locale: "en-IN" },
  { value: "KRW", label: "KRW — South Korean Won", locale: "ko-KR" },
  { value: "SGD", label: "SGD — Singapore Dollar", locale: "en-SG" },
  { value: "HKD", label: "HKD — Hong Kong Dollar", locale: "zh-HK" },
  { value: "AED", label: "AED — UAE Dirham", locale: "ar-AE" },
  { value: "SAR", label: "SAR — Saudi Riyal", locale: "ar-SA" },
  { value: "BRL", label: "BRL — Brazilian Real", locale: "pt-BR" },
  { value: "MXN", label: "MXN — Mexican Peso", locale: "es-MX" },
  { value: "ZAR", label: "ZAR — South African Rand", locale: "en-ZA" },
];

export type Currency = (typeof currencies)[0];
